// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFayIESwZ7njVQBjOx04jMTxhQcy1L7HA',
    appId: '1:945703017398:web:a05f0e8350fb5e8f443f17',
    messagingSenderId: '945703017398',
    projectId: 'moneo-30b0b',
    authDomain: 'moneo-30b0b.firebaseapp.com',
    storageBucket: 'moneo-30b0b.firebasestorage.app',
    measurementId: 'G-ZJ47YLRP25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCRzfIbkkIewBTkdvxASIeX1-bVdhlbBM',
    appId: '1:945703017398:android:4b2a8a00e936b181443f17',
    messagingSenderId: '945703017398',
    projectId: 'moneo-30b0b',
    storageBucket: 'moneo-30b0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpEJ1Lo_roiltz7FJoQk230ABlSijEOzQ',
    appId: '1:945703017398:ios:9595037546daf953443f17',
    messagingSenderId: '945703017398',
    projectId: 'moneo-30b0b',
    storageBucket: 'moneo-30b0b.firebasestorage.app',
    iosBundleId: 'com.example.moneo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpEJ1Lo_roiltz7FJoQk230ABlSijEOzQ',
    appId: '1:945703017398:ios:9595037546daf953443f17',
    messagingSenderId: '945703017398',
    projectId: 'moneo-30b0b',
    storageBucket: 'moneo-30b0b.firebasestorage.app',
    iosBundleId: 'com.example.moneo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFayIESwZ7njVQBjOx04jMTxhQcy1L7HA',
    appId: '1:945703017398:web:633cb4025026fac7443f17',
    messagingSenderId: '945703017398',
    projectId: 'moneo-30b0b',
    authDomain: 'moneo-30b0b.firebaseapp.com',
    storageBucket: 'moneo-30b0b.firebasestorage.app',
    measurementId: 'G-Z85P65SE5T',
  );
}
